//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass
    {
        public int Id { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateUntil { get; set; }
        public int ClientId { get; set; }
        public int CarId { get; set; }
        public decimal FinallyPrice { get; set; }
        public int StatusId { get; set; }
        public decimal Deposit { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual PassStatus PassStatus { get; set; }
    }
}
